== SD card setup
The Raspberry Pi will not start without a properly formatted SD Card, containing the bootloader and a suitable operating system. Many problems with booting the Raspberry Pi are a result of an improperly formatted or corrupted card. Make sure that you insert the card before powering on the Raspberry Pi, and that you shutdown the Raspberry Pi before unplugging the card.

== Flashing the SD Card using Windows

=== Using the Win32DiskImager program

1.  Download the http://www.finnie.org/software/raspberrypi/2015-04-06-ubuntu-trusty.zip[Ubuntu Trusty Image] (http://www.finnie.org/software/raspberrypi/2015-04-06-ubuntu-trusty.zip.asc[GPG signature]) 
2.  Extract the image file from the downloaded .zip file, so you now have "2015-04-06-ubuntu-trusty.img".
3.  Insert the SD card into your SD card reader and check what drive letter it was assigned. You can easily see the drive letter (for example G:) by looking in the left column of Windows Explorer. You can use the SD Card slot (if you have one) or a cheap Adapter in a USB slot.
4.  Download the http://sourceforge.net/projects/win32diskimager[Win32DiskImager] utility (it is also a zip file).

5.  Extract the executable from the zip file and run the Win32DiskImager utility; you may need to run the utility as Administrator! Right-click on the file, and select 'Run as Administrator'
6.  Select the image file you extracted above.
7.  Select the drive letter of the SD card in the device box. If you are using an SD Card slot in your computer (if you have one) and can't see the drive in the Win32DiskImager window, try using a cheap Adapter in a USB slot.

[CAUTION]
====
Be careful to select the correct drive; if you get the wrong one you can destroy your data on the computer's hard disk!
====

8.  Click Write and wait for the write to complete.
9.  Exit the imager and eject the SD card.


