= IR Bracket

These designs:

* link:bracket1.stl[This STL file] may be 3D printed.
* link:bracket1.fcstd[This FreeCAD design] of the bracket.

Another design using the screw hole for mounting:

link:pololu-ir-mount.scad[] &ndash; A right-angle mount for the
link:https://www.pololu.com/product/2474[Pololu GP2Y0A60SZ 10-150cm
sensor]

link:pololu-ir-mount.stl[] &ndash; STL file ready for 3D printing.

This file is set up to print five mounts, but you can edit the file to
remove the duplicates if you only want to print one.

== License

The materials for this class are licensed under the Apache license. See the file LICENSE for details.

Copyright 2015 Marco Walther

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0.

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
