= BT4 Communications Requirements and Design
:toc:

== License

The materials for this class are licensed under the Apache license. See the file LICENSE for details.

Copyright 2015 F Douthit

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0.

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

== Objective

We would like to use Bluetooth 4 low power Communication to broadcast and consume non-private data about our robots. 
Some examples of the sort of data we may wish to share:

* Position
* Orientation
* Synchronization
* Common Time Base

== Requirements

* Written in python. This seems easiest to use across the platforms and does not require compilation for any target platform.
* We will need both host and client code.
* The code should be implemented as ROS nodes, which means we will be able to log and replay this data.
* Synchronization and time base will reside on a 'shared' instance of ROS, which will also likely support the "god's eye".

== Resources

* link:https://developer.bluetooth.org/TechnologyOverview/Pages/Profiles.aspx[Profiles]
* link:http://www.elinux.org/RPi_Bluetooth_LE[Raspberry Pi BT]
* link:https://people.csail.mit.edu/albert/bluez-intro/c212.html[Programming BT with Python]
* link:https://github.com/loeschg/bluetooth-innmotion/tree/master/Application%20Accelerator%20v1.0.1/Android/BLEDemo[Github generic Android BLE app with heart rate variability.]

