:imagesdir: ./images
:toc: macro

= Programming Robots Study Group

toc::[]



== License

The materials for this class are licensed under the Apache license. See the file LICENSE for details.

Copyright 2015, 2016 F Douthit

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0.

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.


== Overview
Robots are coming! Let’s be ready to program them!

This study group is http://wiki.ros.org/[ROS] centric. Class material will be based upon http://releases.ubuntu.com/14.04/[Ubuntu 14.04], http://wiki.ros.org/indigo[ROS Indigo] and http://developer.android.com/index.html[Android]. Other operating systems may work but we chose Ubuntu as it is ROS’ supported platform.

This text is an index into our ROS courseware.

==== link:ROS_Session_1.asciidoc[Session 1]

==== link:ROS_Session_1_TurtleSim_Demo.asciidoc[Session 1 - TurtleSim Demo]

==== link:ROS_Session_2.asciidoc[Session 2]

==== link:ROS_Session_3.asciidoc[Session 3]

