= Robot Base Designs

This directory contains some design files for the robot base plates.
These are simple outlines designed for laser etching or printing onto
paper for scribing onto the desired material. Darren has created more
complete design files showing motor locations and other features that
may be more suitable for your purposes.

== 1. Inkscape files

These were created more recently.

link:robot-base.svg[] &ndash; A base with wheel cutouts

link:robot-top.svg[] &ndash; A circular plate for a 2nd or third deck,
with scribe lines marked for sensor centers at 45&degree; intervals

== 2. Omnigraffle files

These were the original files, created on a Mac. I've printed to PDF if
you don&rsquo;t have Omnigraffle.

link:rosv2-outline.svg[] &ndash; Both base and top place as separate
canvasses. Also includes outlines of RPi and some other components
I am using.

link:rosv2-outline.pdf[] &ndash; Base place with wheel cutouts

link:rosv2-outline-top.pdf[] &ndash; Circular top or middle plate
